name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu_focal:
    name: ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup (Ubuntu packages)
        run: sudo ./setup/ubuntu/install_prereqs.sh
        shell: bash
      - name: setup (QSopt_ex)
        run: ./setup/setup_qsopt-ex.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
